---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get_started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(astrocoords)
```

```{r}
B <- 5
x <- runif(B, 0, 360)
y <- runif(B, -90, 90)
```

# Init different frames

## ICRS

General approach
```{r}
sky_coord(x, y, frame = icrs())

sky_coord(x, y, frame = galactic())
```

Or more convinient method with helpers
```{r}
ra_dec(x, y)

gal_coord(x, y)
```



# Angular separation in arcsec

```{r}
B <- 5
x1 <- runif(B, 0, 360)
y1 <- runif(B, -90, 90)

x2 <- runif(B, 0, 360)
y2 <- runif(B, -90, 90)


ra_dec(x1, y1) |>
  separation(ra_dec(x2, y2))
```

# Convert between frames


```{r}
B <- 5
x3 <- runif(B, 0, 360)
y3 <- runif(B, -90, 90)


sc3 <- ra_dec(c(x3, NA), c(y3, NA))
sc3

sc3 |> 
  transform(galactic())

sc3 |>
  transform(galactic()) |>
  transform(icrs())
```
# Get ra, dec, l, b

```{r}
B <- 3
x4 <- runif(B, 0, 360)
y4 <- runif(B, -90, 90)

x4
ra_dec(x4, y4) |> ra()

y4
ra_dec(x4, y4) |> dec()

x4
gal_coord(x4, y4) |> l()
y4
gal_coord(x4, y4) |> b()

```

