#!/usr/bin/env Rscript

erfa_dir <- "src/erfa"
if (!dir.exists(erfa_dir)) {
  stop("Directory not found: ", erfa_dir, call. = FALSE)
}

erfa_c <- sort(list.files(erfa_dir, pattern = "\\.c$", full.names = FALSE))
if (!length(erfa_c)) {
  stop("No ERFA C sources found in ", erfa_dir, call. = FALSE)
}

erfa_obj <- sub("\\.c$", ".o", file.path("erfa", erfa_c))
wrap_cpp <- sort(list.files("src", pattern = "^wrap_.*\\.cpp$", full.names = FALSE))
wrap_obj <- sub("\\.cpp$", ".o", wrap_cpp)

objects <- c(erfa_obj, "RcppExports.o", wrap_obj)

makevars_lines <- c(
  "# Generated by tools/update_makevars.R. Do not edit by hand.",
  "PKG_CPPFLAGS = -I./erfa",
  "",
  "OBJECTS = \\",
  paste0("\t", objects[-length(objects)], " \\"),
  paste0("\t", objects[length(objects)])
)

writeLines(makevars_lines, "src/Makevars")
writeLines(makevars_lines, "src/Makevars.win")
