// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _astrocoords_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_seps
Rcpp::NumericVector cpp_era_seps(Rcpp::NumericVector lon1, Rcpp::NumericVector lat1, Rcpp::NumericVector lon2, Rcpp::NumericVector lat2);
RcppExport SEXP _astrocoords_cpp_era_seps(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_seps(lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_astrocoords_rcpp_hello_world", (DL_FUNC) &_astrocoords_rcpp_hello_world, 0},
    {"_astrocoords_cpp_era_seps", (DL_FUNC) &_astrocoords_cpp_era_seps, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_astrocoords(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
