// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_era_s2c
Rcpp::NumericMatrix cpp_era_s2c(Rcpp::NumericVector lon, Rcpp::NumericVector lat);
RcppExport SEXP _astrocoords_cpp_era_s2c(SEXP lonSEXP, SEXP latSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat(latSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_s2c(lon, lat));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_icrs2g
Rcpp::List cpp_era_icrs2g(Rcpp::NumericVector ra, Rcpp::NumericVector dec);
RcppExport SEXP _astrocoords_cpp_era_icrs2g(SEXP raSEXP, SEXP decSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ra(raSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dec(decSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_icrs2g(ra, dec));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_g2icrs
Rcpp::List cpp_era_g2icrs(Rcpp::NumericVector l, Rcpp::NumericVector b);
RcppExport SEXP _astrocoords_cpp_era_g2icrs(SEXP lSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_g2icrs(l, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_seps
Rcpp::NumericVector cpp_era_seps(Rcpp::NumericVector lon1, Rcpp::NumericVector lat1, Rcpp::NumericVector lon2, Rcpp::NumericVector lat2);
RcppExport SEXP _astrocoords_cpp_era_seps(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_seps(lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_cal2jd
Rcpp::List cpp_era_cal2jd(Rcpp::IntegerVector year, Rcpp::IntegerVector month, Rcpp::IntegerVector day);
RcppExport SEXP _astrocoords_cpp_era_cal2jd(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day(daySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_cal2jd(year, month, day));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_jd2cal
Rcpp::List cpp_era_jd2cal(Rcpp::NumericVector d1, Rcpp::NumericVector d2);
RcppExport SEXP _astrocoords_cpp_era_jd2cal(SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_jd2cal(d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_dtf2d
Rcpp::List cpp_era_dtf2d(std::string scale, Rcpp::IntegerVector year, Rcpp::IntegerVector month, Rcpp::IntegerVector day, Rcpp::IntegerVector hour, Rcpp::IntegerVector minute, Rcpp::NumericVector second);
RcppExport SEXP _astrocoords_cpp_era_dtf2d(SEXP scaleSEXP, SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP, SEXP minuteSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hour(hourSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type minute(minuteSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_dtf2d(scale, year, month, day, hour, minute, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_d2dtf
Rcpp::List cpp_era_d2dtf(std::string scale, int ndp, Rcpp::NumericVector d1, Rcpp::NumericVector d2);
RcppExport SEXP _astrocoords_cpp_era_d2dtf(SEXP scaleSEXP, SEXP ndpSEXP, SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type ndp(ndpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_d2dtf(scale, ndp, d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_era_dat
Rcpp::List cpp_era_dat(Rcpp::IntegerVector year, Rcpp::IntegerVector month, Rcpp::IntegerVector day);
RcppExport SEXP _astrocoords_cpp_era_dat(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day(daySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_era_dat(year, month, day));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_astrocoords_cpp_era_s2c", (DL_FUNC) &_astrocoords_cpp_era_s2c, 2},
    {"_astrocoords_cpp_era_icrs2g", (DL_FUNC) &_astrocoords_cpp_era_icrs2g, 2},
    {"_astrocoords_cpp_era_g2icrs", (DL_FUNC) &_astrocoords_cpp_era_g2icrs, 2},
    {"_astrocoords_cpp_era_seps", (DL_FUNC) &_astrocoords_cpp_era_seps, 4},
    {"_astrocoords_cpp_era_cal2jd", (DL_FUNC) &_astrocoords_cpp_era_cal2jd, 3},
    {"_astrocoords_cpp_era_jd2cal", (DL_FUNC) &_astrocoords_cpp_era_jd2cal, 2},
    {"_astrocoords_cpp_era_dtf2d", (DL_FUNC) &_astrocoords_cpp_era_dtf2d, 7},
    {"_astrocoords_cpp_era_d2dtf", (DL_FUNC) &_astrocoords_cpp_era_d2dtf, 4},
    {"_astrocoords_cpp_era_dat", (DL_FUNC) &_astrocoords_cpp_era_dat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_astrocoords(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
