# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_era_icrs2g <- function(ra, dec) {
    .Call(`_astrocoords_cpp_era_icrs2g`, ra, dec)
}

cpp_era_g2icrs <- function(l, b) {
    .Call(`_astrocoords_cpp_era_g2icrs`, l, b)
}

cpp_era_seps <- function(lon1, lat1, lon2, lat2) {
    .Call(`_astrocoords_cpp_era_seps`, lon1, lat1, lon2, lat2)
}

cpp_era_cal2jd <- function(year, month, day) {
    .Call(`_astrocoords_cpp_era_cal2jd`, year, month, day)
}

cpp_era_jd2cal <- function(d1, d2) {
    .Call(`_astrocoords_cpp_era_jd2cal`, d1, d2)
}

cpp_era_dtf2d <- function(scale, year, month, day, hour, minute, second) {
    .Call(`_astrocoords_cpp_era_dtf2d`, scale, year, month, day, hour, minute, second)
}

cpp_era_d2dtf <- function(scale, ndp, d1, d2) {
    .Call(`_astrocoords_cpp_era_d2dtf`, scale, ndp, d1, d2)
}

cpp_era_dat <- function(year, month, day) {
    .Call(`_astrocoords_cpp_era_dat`, year, month, day)
}

